import { Car } from './types'

export const INVENTORY: Car[] = [
  {
    id: '1',
    make: 'Ferrari',
    model: '812 Superfast',
    year: 2023,
    mileage: '1,240 miles',
    price: 445000,
    category: ['sports', 'luxury'],
    badge: 'Featured',
    status: 'available',
    engine: '6.2L V12',
    transmission: 'Automatic',
    drivetrain: 'Rear-Wheel Drive',
    color: 'Rosso Corsa',
    seats: 2,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=900&q=80'],
    description: 'Extraordinary performance vehicle with handcrafted details and cutting-edge technology.',
    featured: true,
  },
  {
    id: '2',
    make: 'Rolls-Royce',
    model: 'Ghost',
    year: 2022,
    mileage: '3,890 miles',
    price: 365000,
    category: ['sedan', 'luxury'],
    badge: 'Premium',
    status: 'available',
    engine: '6.7L Twin-Turbo V12',
    transmission: 'Automatic',
    drivetrain: 'Rear-Wheel Drive',
    color: 'Arctic White',
    seats: 5,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&q=80'],
    description: 'Ultimate expression of automotive elegance with bespoke customization options.',
    featured: true,
  },
  {
    id: '3',
    make: 'Lamborghini',
    model: 'Huracán EVO',
    year: 2024,
    mileage: '540 miles',
    price: 665000,
    category: ['sports', 'luxury'],
    badge: 'New Arrival',
    status: 'available',
    engine: '5.2L V10',
    transmission: 'Automatic',
    drivetrain: 'All-Wheel Drive',
    color: 'Nero Noctis',
    seats: 2,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=900&q=80'],
    description: 'Next-generation hypercar combining Italian passion with cutting-edge performance.',
    featured: true,
  },
  {
    id: '4',
    make: 'BMW',
    model: '7 Series M Sport',
    year: 2023,
    mileage: '2,150 miles',
    price: 185000,
    category: ['sedan', 'luxury'],
    badge: 'Premium',
    status: 'available',
    engine: '3.0L Inline-6 Turbo',
    transmission: '8-Speed Auto',
    drivetrain: 'All-Wheel Drive',
    color: 'Frozen Black Metallic',
    seats: 5,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&q=80'],
    description: 'Performance sedan with extraordinary power and luxurious appointments throughout.',
    featured: false,
  },
  {
    id: '5',
    make: 'Mercedes-Benz',
    model: 'AMG G63',
    year: 2023,
    mileage: '4,320 miles',
    price: 175000,
    category: ['suv', 'luxury'],
    badge: 'Low Mileage',
    status: 'available',
    engine: '4.0L Twin-Turbo V8',
    transmission: 'Automatic',
    drivetrain: 'All-Wheel Drive',
    color: 'Obsidian Black',
    seats: 5,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=900&q=80'],
    description: 'Icon of luxury and capability with aggressive styling and sublime performance.',
    featured: false,
  },
  {
    id: '6',
    make: 'Porsche',
    model: '911 Turbo S',
    year: 2024,
    mileage: '890 miles',
    price: 295000,
    category: ['sports', 'luxury'],
    badge: 'Rare',
    status: 'available',
    engine: '3.8L Twin-Turbo Flat-Six',
    transmission: 'Automatic',
    drivetrain: 'All-Wheel Drive',
    color: 'Python Green',
    seats: 2,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=900&q=80'],
    description: 'Pinnacle of sports car engineering with track-ready performance and luxury comfort.',
    featured: false,
  },
  {
    id: '7',
    make: 'Aston Martin',
    model: 'DB12',
    year: 2023,
    mileage: '1,680 miles',
    price: 325000,
    category: ['sports', 'luxury'],
    badge: 'Featured',
    status: 'available',
    engine: '4.0L Twin-Turbo V8',
    transmission: 'Automatic',
    drivetrain: 'Rear-Wheel Drive',
    color: 'Saffron',
    seats: 2,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=900&q=80'],
    description: 'British elegance meets raw performance in a timeless grand touring masterpiece.',
    featured: false,
  },
  {
    id: '8',
    make: 'Bentley',
    model: 'Continental GT',
    year: 2023,
    mileage: '2,890 miles',
    price: 245000,
    category: ['sedan', 'luxury'],
    badge: 'Premium',
    status: 'available',
    engine: '6.0L Twin-Turbo W12',
    transmission: 'Automatic',
    drivetrain: 'All-Wheel Drive',
    color: 'Pearl White',
    seats: 4,
    fuel: 'Gasoline',
    images: ['https://images.unsplash.com/photo-1625047509248-ec889cbff17f?w=900&q=80'],
    description: 'Handcrafted British luxury with sublime craftsmanship and uncompromising performance.',
    featured: false,
  },
  {
    id: '9',
    make: 'Range Rover',
    model: 'Autobiography',
    year: 2023,
    mileage: '3,100 miles',
    price: 185000,
    category: ['suv', 'luxury'],
    badge: 'New Arrival',
    status: 'available',
    engine: '3.0L D350 MHEV',
    transmission: '8-Speed Auto',
    drivetrain: '4WD',
    color: 'Santorini Black',
    seats: 5,
    fuel: 'Diesel',
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=900&q=80'],
    description: 'The pinnacle of luxury SUV motoring. Unmatched refinement, capability and presence.',
    featured: false,
  },
]

export const ALL_CATEGORIES = [
  { id: 'sedan', label: 'Sedans' },
  { id: 'suv', label: 'SUVs' },
  { id: 'sports', label: 'Sports Cars' },
  { id: 'luxury', label: 'Luxury' },
]

export const TEAM_MEMBERS = [
  {
    id: '1',
    name: 'Michael Davis',
    role: 'Founder & Principal Broker',
    bio: 'Over eight years of automotive expertise and an unwavering passion for exceptional vehicles.',
    image: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=500&q=80',
  },
]